apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.repoName }}
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
